name: flutter_node_auth
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #for storing settings and user token securely
  flutter_secure_storage: ^4.2.1
  #for state management
  get: ^4.3.8
  #for http requests to server
  dio: ^4.0.0
  #for picking image from gallery or taking picture from camera
  image_picker: ^0.8.4+2
  #for cropping image 
  image_cropper: ^1.4.1
  #for displaying images like pinterest
  flutter_staggered_grid_view: ^0.4.0
  #for caching images from network
  cached_network_image: ^3.1.0
  #for adding pull to refresh and pull up to fetch more
  pull_to_refresh: ^2.0.0
  #for displaying google ads
  google_mobile_ads: ^0.13.5
  #for page transition animation
  transition: ^2.0.2
  #for modifying date object
  intl: ^0.17.0
  #for displaying images in carousel form
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

  
  

  
  

 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
